### ISSUE TITLE
README.md step 8, relative file path to ProductConsumerPactTest.java

### ISSUE THREAD

**Issue by Perfspec** [pact-foundation/pact-workshop-jvm-spring#13]
https://github.com/pact-foundation/pact-workshop-jvm-spring/tree/step8
Commit ID: e2babbe0662ba5f810a236a5b19ffb394cf4aebe

README.md line 642 could use `consumer/src/test/java/au/com/dius/pactworkshop/consumer/ProductConsumerPactTest.java` instead of `consumer/src/api.pact.spec.js`

**Comment by uglyog** [comment]
Fixed. Thanks!
