### ISSUE TITLE
Implementing body matchers - for complex responses

### ISSUE THREAD

**Issue by tl-madhulika-mitra** [pact-foundation/pact-workshop-jvm-spring#20]
When I looked at the PactDslJsonBody for implementing matchers , it could get difficult to keep for complex responses. Is there a means to just mention that match as per type ?
.WillRespondWith(new ProviderServiceResponse
{
    Status = 201,
    Headers = new Dictionary<string, object> {{"Content-Type", "application/json; charset=utf-8"}},
    Body = Match.Type(paymentResponse)
});

**Comment by YOU54F** [comment]
Closing this in favour of https://github.com/pact-foundation/pact-jvm/issues/1541
